#!/bin/bash
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Running pre push to master check...${NC}"

echo -e "${YELLOW}Trying to build tests project...${NC}"

# build the project
dotnet build

# $? is a shell variable which stores the return code from what we just ran
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}Failed to build the project, please fix this and push again${NC}"
    echo ""
    exit $rc
fi

#just list directories separated by space
declare -a unitTestProjectDirectories=("Survey.Business.XUnit.Test" "Survey.Business.XUnit.Test2")

for unitTestProjectDirectory in "${unitTestProjectDirectories[@]}"
do
	cd $unitTestProjectDirectory
	
	echo -e "${YELLOW}Running unit tests for $unitTestProjectDirectory...${NC}"
	echo ""
	
	# run the unit tests
	dotnet test
	
	# $? is a shell variable which stores the return code from what we just ran
	rc=$?
	if [[ $rc != 0 ]] ; then
		# A non-zero return code means an error occurred, so tell the user and exit
		echo -e "${RED}Unit tests failed, please fix and push again${NC}"
		echo ""
		exit $rc
	fi
	
	cd ..
	
   # or do whatever with individual element of the array
done    

# Everything went OK so we can exit with a zero
echo -e "${GREEN}Pre push check passed!${NC}"
echo ""
exit 0