export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_SURVEY = 'FETCH_SURVEY';
export const CREATE_SURVEY = 'CREATE_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';

export const FETCH_SURVEY_PASSINGS = 'FETCH_SURVEY_PASSINGS';